version: '3.8'

services:
  kanban-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./target:/app/target
    environment:
      - SPRING_PROFILES_ACTIVE=prod